name: Setup and Automate Luna Login

on:
  push:

jobs:
  setup-and-launch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: false

      # Step 2: Install necessary dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y x11vnc xvfb unzip 7zip python3 python3-pip

      # Step 3: Install Brave Browser
      - name: Install Brave Browser
        run: |
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
          sudo apt-get update
          sudo apt-get install -y brave-browser

      # Step 4: Install Selenium and WebDriver
      - name: Install Selenium and WebDriver
        run: |
          sudo pip3 install selenium pyotp
          sudo apt-get install -y chromium-chromedriver

      # Step 5: Install Cloudflared
      - name: Install Cloudflared
        run: |
          sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      # Step 6: Setup Cloudflare Credentials
      - name: Setup Cloudflare Credentials
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_CERT_PEM }}" > ~/.cloudflared/cert.pem
          chmod 600 ~/.cloudflared/cert.pem

      # Step 7: Start Xvfb
      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &

      # Step 8: Start x11vnc
      - name: Start x11vnc
        run: |
          export DISPLAY=:99
          x11vnc -display :99 -N -forever -shared &

      # Step 9: Create or Modify GroupPolicy.json for Brave
      - name: Create or Modify GroupPolicy.json
        run: |
          sudo mkdir -p /etc/brave/policies/managed
          echo '{
            "ExtensionSettings": {
              "*": {
                "installation_mode": "blocked"
              },
              "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
                "installation_mode": "force_installed",
                "update_url": "https://clients2.google.com/service/update2/crx"
              },
              "jinjaccalgkegednnccohejagnlnfdag": {
                "installation_mode": "force_installed",
                "update_url": "https://clients2.google.com/service/update2/crx"
              }
            },
            "TorDisabled": true,
            "BraveVPNDisabled": true,
            "BraveRewardsDisabled": true,
            "BraveWalletDisabled": true,
            "MetricsReportingEnabled": false,
            "DefaultBrowserSettingEnabled": false,
            "HomepageIsNewTabPage": true,
            "NewTabPageLocation": "about:blank"
          }' | sudo tee /etc/brave/policies/managed/GroupPolicy.json

      # Step 10: Launch Brave Browser
      - name: Launch Brave Browser
        run: |
          export DISPLAY=:99
          nohup brave-browser --no-sandbox "${{ secrets.SECRET_URL }}" &

      # Step 11: Check, Delete Existing Tunnel, Create New Tunnel, and Route DNS
      - name: Check, Delete Existing Tunnel, Create New Tunnel, and Route DNS
        run: |
          # Define tunnel name and hostname from secrets
          TUNNEL_NAME="github-actions-tunnel"
          HOSTNAME="${{ secrets.VNC_HOSTNAME }}"

          # Check if the tunnel already exists
          EXISTING_TUNNEL=$(cloudflared tunnel list | grep "$TUNNEL_NAME" || true)

          if [ -n "$EXISTING_TUNNEL" ]; then
            # Delete the existing tunnel
            TUNNEL_ID=$(echo "$EXISTING_TUNNEL" | awk '{print $1}')
            echo "Tunnel exists. Deleting tunnel with ID: $TUNNEL_ID..."
            cloudflared tunnel delete "$TUNNEL_ID"
            echo "Tunnel deleted."
          fi

          # Create a new tunnel
          echo "Creating a new tunnel..."
          cloudflared tunnel create "$TUNNEL_NAME"
          TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
          echo "Tunnel ID: $TUNNEL_ID"

          # Create config.yml using multiple echo statements for proper indentation
          mkdir -p ~/.cloudflared
          {
            echo "tunnel: $TUNNEL_ID"
            echo "credentials-file: /home/runner/.cloudflared/$TUNNEL_ID.json"
            echo ""
            echo "ingress:"
            echo "  - hostname: \"$HOSTNAME\""
            echo "    service: tcp://localhost:5900"
            echo "  - service: http_status:404"
          } > ~/.cloudflared/config.yml

          echo "Cloudflare tunnel configuration created."

          # Route the tunnel to your custom domain using Cloudflared CLI with --overwrite-dns option
          echo "Routing tunnel to your custom domain..."
          cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$HOSTNAME"
          echo "DNS record created successfully."

      # Step 12: Start Cloudflared Tunnel
      - name: Start Cloudflared Tunnel
        run: |
          nohup cloudflared tunnel --config ~/.cloudflared/config.yml run github-actions-tunnel &
          sleep 10  # Allow time for the tunnel to establish

      # Step 13: Serve user.js Script Locally
      - name: Serve user.js Script Locally
        run: |
          echo "${{ secrets.USER_JS }}" > user.js
          python3 -m http.server 8000 &

      # Step 14: Automatically Login to Luna and Install user.js via Violentmonkey
      - name: Automatically Login to Luna and Install user.js
        run: |
          echo 'import time
          import pyotp
          from selenium import webdriver
          from selenium.webdriver.common.keys import Keys
          from selenium.webdriver.common.by import By
          from selenium.webdriver.support.ui import WebDriverWait
          from selenium.webdriver.support import expected_conditions as EC

          # Set up options for Brave browser
          options = webdriver.ChromeOptions()
          options.binary_location = "/usr/bin/brave-browser"
          options.add_argument("--no-sandbox")
          options.add_argument("--headless")
          options.add_argument("--disable-dev-shm-usage")
          options.add_argument("--disable-gpu")
          options.add_argument("--remote-debugging-port=9222")

          # Set up the WebDriver
          driver = webdriver.Chrome(options=options)
          driver.get("${{ secrets.SECRET_URL }}")

          # Wait for the login page to load and input credentials
          wait = WebDriverWait(driver, 10)
          email_field = wait.until(EC.presence_of_element_located((By.ID, "ap_email")))
          email_field.send_keys("${{ secrets.AMAZON_EMAIL }}")
          email_field.send_keys(Keys.RETURN)

          # Wait for the password field to load and input password
          password_field = wait.until(EC.presence_of_element_located((By.ID, "ap_password")))
          password_field.send_keys("${{ secrets.AMAZON_PASSWORD }}")
          password_field.send_keys(Keys.RETURN)

          # Generate OTP code using TOTP
          totp = pyotp.TOTP("${{ secrets.AMAZON_TOTP_SECRET }}")
          otp_code = totp.now()

          # Handle 2FA if required
          otp_field = wait.until(EC.presence_of_element_located((By.ID, "auth-mfa-otpcode")))
          otp_field.send_keys(otp_code)
          otp_field.send_keys(Keys.RETURN)

          # Install the user.js script via Violentmonkey
          driver.get("chrome-extension://jinjaccalgkegednnccohejagnlnfdag/options.html#/install")
          script_area = wait.until(EC.presence_of_element_located((By.TAG_NAME, "textarea")))
          script_area.clear()
          script_area.send_keys("""http://localhost:8000/user.js""")
          install_button = driver.find_element(By.XPATH, "//button[contains(text(), 'Install')]")
          install_button.click()

          # Keep the browser running
          while True:
              time.sleep(1000)' > automate_login.py
          python3 automate_login.py

      # Step 15: Keep Services Running Indefinitely
      - name: Keep Services Running
        run: |
          while true; do sleep 1000; done
