name: Setup and Automate Browser Operations

on:
  push:
    branches:
      - main

jobs:
  setup-and-launch:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install System Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            x11vnc \
            xvfb \
            unzip \
            curl \
            wget \
            gnupg \
            libxss1 \
            libnss3 \
            libgbm-dev \
            libasound2

      # 4. Install Python Packages and Playwright
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pyotp requests Pillow
          playwright install chromium
          playwright install-deps

      # 5. Install Cloudflared
      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      # 6. Set up Cloudflare credentials
      - name: Setup Cloudflare Credentials
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_CERT_PEM }}" > ~/.cloudflared/cert.pem
          chmod 600 ~/.cloudflared/cert.pem

      # 7. Start Xvfb and x11vnc
      - name: Start Virtual Display and VNC
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          x11vnc -display :99 -N -forever -shared &
          sleep 5

      # 8. Extract Cookies.zip
      - name: Extract Cookies.zip
        env:
          BRAVE_ZIP_PASSWORD: ${{ secrets.BRAVE_ZIP_PASSWORD }}
        run: |
          mkdir -p ~/.config/microsoft-edge/Default
          7z x Cookies.zip -o~/.config/microsoft-edge/Default -p"$BRAVE_ZIP_PASSWORD"

      # 8. Configure Edge Policies
      - name: Configure Edge Policies
        run: |
          sudo mkdir -p /etc/opt/edge/policies/managed
          sudo tee /etc/opt/edge/policies/managed/policy.json > /dev/null << 'EOL'
          {
            "ExtensionInstallForcelist": [
              "eeagobfjdenkkddmbclomhiblgggliao;https://edge.microsoft.com/extensionwebstorebase/v1/crx"
            ],
            "ExtensionInstallAllowlist": ["*"],
            "ExtensionManifestV2Availability": 2,
            "ExtensionsOnEdgeAdditionsEnabled": true,
            "DeveloperToolsAvailability": 1,
            "EdgeCollectionsEnabled": false,
            "EdgeShoppingAssistantEnabled": false,
            "ShowMicrosoftRewards": false,
            "ShowRecommendationsEnabled": false,
            "EdgeFeedbackEnabled": false,
            "AutofillAddressEnabled": false,
            "AutofillCreditCardEnabled": false,
            "PasswordManagerEnabled": false,
            "SmartScreenEnabled": false,
            "ExperimentationAndConfigurationServiceControl": {
              "no-reports": true
            }
          }
          EOL

      # 9. Serve userscript Locally
      - name: Serve Userscript Locally
        env:
          USER_JS: ${{ secrets.USER_JS }}
        run: |
          echo "$USER_JS" > main.user.js
          python3 -m http.server 8000 &
          sleep 2
          curl -f http://localhost:8000/main.user.js || exit 1

      # 10. Install Userscript
      - name: Install Userscript
        env:
          DISPLAY: :99
        run: |
          echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] Starting automation script creation..."
          
          cat <<'EOF' > automation.py
          import time
          from datetime import datetime
          from playwright.sync_api import sync_playwright, TimeoutError

          def log_debug(message):
              timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
              print(f"[{timestamp}] {message}")

          def check_violentmonkey(context, max_wait_time=300):  # 5 minutes timeout
              log_debug("Checking if Violentmonkey is installed...")
              start_time = time.time()
              
              while time.time() - start_time < max_wait_time:
                  try:
                      test_page = context.new_page()
                      response = test_page.goto("extension://eeagobfjdenkkddmbclomhiblgggliao/options/index.html", timeout=5000)
                      test_page.close()
                      
                      if response and response.ok:
                          log_debug("✓ Violentmonkey is installed and accessible")
                          return True
                          
                  except Exception as e:
                      elapsed = int(time.time() - start_time)
                      log_debug(f"⟳ Waiting for Violentmonkey to be installed... ({elapsed}s/{max_wait_time}s)")
                      time.sleep(5)
                      
              raise TimeoutError("Violentmonkey installation check timed out after 5 minutes")

          def install_userscript(context, max_wait_time=300):
              log_debug("=== Starting Userscript Installation ===")
              
              # First check if Violentmonkey is installed
              if not check_violentmonkey(context):
                  raise Exception("Violentmonkey is not installed")
              
              start_time = time.time()
              page = context.new_page()
              
              while time.time() - start_time < max_wait_time:
                  try:
                      log_debug("Loading main.user.js...")
                      page.goto("http://localhost:8000/main.user.js", timeout=10000)
                      
                      log_debug(f"Current URL: {page.url}")
                      
                      # Wait for Violentmonkey confirmation page
                      if "eeagobfjdenkkddmbclomhiblgggliao/confirm" in page.url:
                          log_debug("✓ Violentmonkey confirmation page detected")
                          
                          # Click Install button
                          install_button = page.wait_for_selector('button#confirm[data-hotkey="Ctrl-Enter"], button#confirm[data-hotkey="⌘Enter"]', timeout=5000)
                          if install_button:
                              install_button.click()
                              log_debug("✓ Clicked Install button")
                              
                              # Wait 1 second and click Close button
                              time.sleep(1)
                              close_button = page.wait_for_selector('button:has-text("Close")', timeout=5000)
                              if close_button:
                                  close_button.click()
                                  log_debug("✓ Clicked Close button")
                              
                              page.close()
                              return True
                      
                      elapsed = int(time.time() - start_time)
                      log_debug(f"Waiting for confirmation page... ({elapsed}s/{max_wait_time}s)")
                      time.sleep(1)
                      
                  except Exception as e:
                      log_debug(f"Error during installation: {str(e)}")
                      time.sleep(1)
              
              raise TimeoutError("Userscript installation timed out after 5 minutes")

          def main():
              log_debug("Starting main automation process")
              
              with sync_playwright() as p:
                  log_debug("Launching browser...")
                  try:
                      context = p.chromium.launch_persistent_context(
                          user_data_dir="/tmp/edge-data",
                          channel="msedge",
                          headless=False,
                          args=[
                              "--no-sandbox",
                              "--disable-dev-shm-usage",
                              "--start-maximized",
                              "--disable-features=ExtensionsToolbarMenu",
                              "--no-default-browser-check",
                              "--no-first-run",
                              "--disable-extensions-http-throttling"
                          ],
                          viewport={"width": 1920, "height": 1080},
                          timeout=30000
                      )
                      log_debug("Browser launched successfully")

                      if install_userscript(context):
                          log_debug("✓ Userscript installation successful")
                          
                          log_debug("Navigating to Luna...")
                          page = context.new_page()
                          page.goto("https://luna.amazon.de", timeout=30000)
                          log_debug("✓ Navigation complete - userscript will handle the rest")
                      
                  except Exception as e:
                      log_debug(f"✗ Automation failed: {e}")
                      raise
                  finally:
                      log_debug("Automation script completed")
                      pass

          if __name__ == "__main__":
              log_debug("Script started")
              main()
          EOF

          echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] Automation script created, starting Python execution..."
          python3 automation.py

      # 11. Launch Edge for VNC Access
      - name: Launch Edge Browser
        env:
          DISPLAY: :99
        run: |
          microsoft-edge \
            --no-sandbox \
            --user-data-dir=/tmp/edge-data \
            --disable-features=ExtensionsToolbarMenu \
            --disable-extensions-http-throttling \
            --disable-popup-blocking \
            --no-default-browser-check \
            --no-first-run \
            "${{ secrets.SECRET_URL }}" &
          
          sleep 5

      # 12. Manage Cloudflared Tunnel
      - name: Manage Cloudflared Tunnel
        run: |
          TUNNEL_NAME="github-actions-tunnel"
          HOSTNAME="${{ secrets.VNC_HOSTNAME }}"

          EXISTING_TUNNEL=$(cloudflared tunnel list | grep "$TUNNEL_NAME" || true)
          if [ -n "$EXISTING_TUNNEL" ]; then
            TUNNEL_ID=$(echo "$EXISTING_TUNNEL" | awk '{print $1}')
            echo "Existing tunnel: $TUNNEL_ID. Deleting..."
            cloudflared tunnel delete "$TUNNEL_ID"
          fi

          cloudflared tunnel create "$TUNNEL_NAME"
          TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')

          mkdir -p ~/.cloudflared
          cat <<EOL > ~/.cloudflared/config.yml
          tunnel: $TUNNEL_ID
          credentials-file: /home/runner/.cloudflared/$TUNNEL_ID.json
          
          ingress:
            - hostname: "$HOSTNAME"
              service: tcp://localhost:5900
            - service: http_status:404
          EOL

          cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$HOSTNAME"

      # 13. Start Cloudflared
      - name: Start Cloudflared
        run: |
          nohup cloudflared tunnel --config ~/.cloudflared/config.yml run "github-actions-tunnel" &
          sleep 10

      # 14. Keep the container running
      - name: Keep Service Running
        run: |
          echo "Workflow complete; keeping container alive..."
          while true; do sleep 1000; done
