name: Setup and Automate Browser Operations

on:
  push:
    branches:
      - main

jobs:
  setup-and-launch:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install System Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            x11vnc \
            xvfb \
            unzip \
            curl \
            wget \
            gnupg \
            libxss1 \
            libnss3 \
            libgbm-dev \
            libasound2

      # 4. Install Python Packages and Playwright
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pyotp requests Pillow
          playwright install chromium
          playwright install-deps

      # 5. Install Cloudflared
      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      # 6. Set up Cloudflare credentials
      - name: Setup Cloudflare Credentials
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARE_CERT_PEM }}" > ~/.cloudflared/cert.pem
          chmod 600 ~/.cloudflared/cert.pem

      # 7. Start Xvfb and x11vnc
      - name: Start Virtual Display and VNC
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          x11vnc -display :99 -N -forever -shared &
          sleep 5

      # 8. Configure Edge and Extensions
      - name: Configure Edge Policies
        run: |
          sudo mkdir -p /etc/opt/edge/policies/managed
          sudo tee /etc/opt/edge/policies/managed/policy.json > /dev/null <<EOL
          {
            "ExtensionInstallForcelist": [
              "jinjaccalgkegednnccohejagnlnfdag;https://clients2.google.com/service/update2/crx",
              "hlkenndednhfkekhgcdicdfddnkalmdm;https://clients2.google.com/service/update2/crx"
            ],
            "ExtensionInstallAllowlist": ["*"],
            "ExtensionManifestV2Availability": 2,
            "ExtensionsOnEdgeAdditionsEnabled": true,
            "DeveloperToolsAvailability": 1,
            "EdgeCollectionsEnabled": false,
            "EdgeShoppingAssistantEnabled": false,
            "ShowMicrosoftRewards": false,
            "ShowRecommendationsEnabled": false,
            "EdgeFeedbackEnabled": false,
            "AutofillAddressEnabled": false,
            "AutofillCreditCardEnabled": false,
            "PasswordManagerEnabled": false,
            "SmartScreenEnabled": false,
            "ExperimentationAndConfigurationServiceControl": {
              "no-reports": true
            }
          }
          EOL

      # 9. Serve userscript Locally
      - name: Serve Userscript Locally
        env:
          USER_JS: ${{ secrets.USER_JS }}
        run: |
          echo "$USER_JS" > main.user.js
          python3 -m http.server 8000 &
          sleep 2
          curl -f http://localhost:8000/main.user.js || exit 1

      # 10. Cookie Import and Userscript Installation
      - name: Handle Cookie Import and Userscript Installation
        env:
          AZ_COOKIES: ${{ secrets.AZ_COOKIES }}
          DISPLAY: :99
        run: |
          cat <<EOF > automation.py
          import time
          import json
          import os
          import requests
          from playwright.sync_api import sync_playwright

          def verify_local_server():
              try:
                  response = requests.get('http://localhost:8000/main.user.js')
                  response.raise_for_status()
                  print("✓ Local server is running and main.user.js is accessible")
                  return True
              except Exception as e:
                  print(f"✗ Error accessing local server: {e}")
                  return False

          def wait_for_extension(context, extension_id, extension_name, timeout=120):
              print(f"\nWaiting for {extension_name} ({extension_id}) to be ready...")
              start_time = time.time()
              
              while time.time() - start_time < timeout:
                  try:
                      # Try different extension pages
                      pages_to_try = [
                          f"chrome-extension://{extension_id}/popup.html",
                          f"chrome-extension://{extension_id}/options.html",
                          f"chrome-extension://{extension_id}/index.html"
                      ]
                      
                      for url in pages_to_try:
                          try:
                              page = context.new_page()
                              response = page.goto(url, timeout=5000)
                              if response and response.ok:
                                  print(f"✓ {extension_name} is ready (accessed {url})")
                                  page.close()
                                  return True
                              page.close()
                          except Exception:
                              continue
                              
                  except Exception as e:
                      pass
                      
                  # Every 10 seconds, try to trigger extension installation check
                  if int(time.time() - start_time) % 10 == 0:
                      try:
                          check_page = context.new_page()
                          check_page.goto("edge://extensions")
                          time.sleep(1)
                          check_page.close()
                      except:
                          pass
                          
                  print(f"⟳ Still waiting for {extension_name}... ({int(time.time() - start_time)}s/{timeout}s)")
                  time.sleep(2)
                  
              print(f"✗ Timeout waiting for {extension_name}")
              return False

          def import_cookies(context, page):
              print("\n=== Starting Cookie Import ===")
              cookies_json = os.getenv('AZ_COOKIES')
              if not cookies_json:
                  raise ValueError("✗ No cookies found in environment variables")

              # Wait for Cookie-Editor with increased timeout
              cookie_editor_id = "hlkenndednhfkekhgcdicdfddnkalmdm"
              if not wait_for_extension(context, cookie_editor_id, "Cookie-Editor"):
                  raise Exception("✗ Cookie-Editor extension not available")

              # Visit extensions page to ensure everything is loaded
              print("Checking extensions page...")
              extensions_page = context.new_page()
              extensions_page.goto("edge://extensions")
              time.sleep(5)
              extensions_page.close()

              # Navigate to Luna
              print("Navigating to Luna...")
              page.goto("https://luna.amazon.de")
              time.sleep(5)

              # Multiple attempts to open Cookie-Editor
              max_attempts = 3
              for attempt in range(max_attempts):
                  print(f"Attempt {attempt + 1}/{max_attempts} to open Cookie-Editor...")
                  page.keyboard.press("Alt+Shift+C")
                  time.sleep(2)
                  
                  import_button = page.get_by_role("button", name="Import")
                  if import_button.is_visible():
                      print("✓ Cookie-Editor opened successfully")
                      import_button.click()
                      time.sleep(1)
                      page.keyboard.type(cookies_json)
                      page.keyboard.press("Enter")
                      time.sleep(2)
                      break
                  else:
                      print("Cookie-Editor not responding, retrying...")
                      if attempt == max_attempts - 1:
                          raise Exception("✗ Failed to open Cookie-Editor after multiple attempts")
                      time.sleep(3)

              # Verify cookies
              print("Refreshing page to apply cookies...")
              page.reload()
              time.sleep(5)

              if page.locator("#item_secondary_nav_button_sign_in").is_visible():
                  raise Exception("✗ Login failed - Still seeing sign-in button")
              
              print("✓ Successfully imported cookies and logged in")
              return True

          def install_userscript(context, page):
              print("\n=== Starting Userscript Installation ===")
              
              # Wait for Violentmonkey
              violentmonkey_id = "jinjaccalgkegednnccohejagnlnfdag"
              if not wait_for_extension(page, violentmonkey_id, "Violentmonkey"):
                  raise Exception("✗ Violentmonkey extension not available")

              try:
                  install_page = context.new_page()
                  print("Loading main.user.js...")
                  response = install_page.goto("http://localhost:8000/main.user.js", wait_until="domcontentloaded")
                  
                  if response and response.ok:
                      print("✓ Successfully loaded main.user.js")
                      
                      # Wait for and click install button
                      install_button = install_page.wait_for_selector("xpath=//button[contains(text(), 'Install')]", timeout=10000)
                      if install_button:
                          install_button.click()
                          print("✓ Clicked install button")
                          time.sleep(2)
                          
                          # Handle confirmation if needed
                          confirm_button = install_page.get_by_role("button", name="OK", exact=True)
                          if confirm_button.is_visible():
                              confirm_button.click()
                              print("✓ Clicked confirmation button")
                          
                          # Verify installation
                          time.sleep(2)
                          violentmonkey_page = context.new_page()
                          violentmonkey_page.goto(f"chrome-extension://{violentmonkey_id}/options.html")
                          time.sleep(2)
                          
                          if violentmonkey_page.get_by_text("main.user.js").is_visible():
                              print("✓ Userscript installation verified")
                          else:
                              raise Exception("✗ Userscript not found in Violentmonkey")
                              
                          violentmonkey_page.close()
                      else:
                          raise Exception("✗ Install button not found")
                  else:
                      raise Exception(f"✗ Failed to load main.user.js: {response.status if response else 'No response'}")
                  
                  install_page.close()
                  return True
                  
              except Exception as e:
                  print(f"✗ Error during script installation: {e}")
                  raise
          def main():
              if not verify_local_server():
                  raise Exception("✗ Local server check failed")

              with sync_playwright() as p:
                  # Launch with increased timeouts
                  context = p.chromium.launch_persistent_context(
                      user_data_dir="/tmp/edge-data",
                      channel="msedge",
                      headless=False,
                      args=[
                          "--no-sandbox",
                          "--disable-dev-shm-usage",
                          "--start-maximized",
                          "--disable-features=ExtensionsToolbarMenu",
                          "--no-default-browser-check",
                          "--no-first-run",
                          "--disable-extensions-http-throttling"
                      ],
                      viewport={"width": 1920, "height": 1080},
                      timeout=120000  # Increase timeout to 120 seconds
                  )

                  try:
                      # Visit extensions page first to trigger extension loading
                      print("Initializing extensions...")
                      init_page = context.new_page()
                      init_page.goto("edge://extensions")
                      time.sleep(10)
                      init_page.close()

                      page = context.new_page()
                      
                      if import_cookies(context, page):
                          print("\n✓ Cookie import successful")
                          if install_userscript(context, page):
                              print("\n✓ Userscript installation successful")
                              
                      print("\n=== Final Verification ===")
                      page.bring_to_front()
                      page.reload()
                      time.sleep(3)
                      print("✓ Automation completed successfully")
                      
                  except Exception as e:
                      print(f"\n✗ Automation failed: {e}")
                      raise
                  finally:
                      pass

          if __name__ == "__main__":
              main()
          EOF

          python3 automation.py

      # 11. Launch Edge for VNC Access
      - name: Launch Edge Browser
        env:
          AZ_COOKIES: ${{ secrets.AZ_COOKIES }}
          DISPLAY: :99
        run: |
          # Launch Edge
          microsoft-edge \
            --no-sandbox \
            --user-data-dir=/tmp/edge-data \
            --disable-features=ExtensionsToolbarMenu \
            --disable-extensions-http-throttling \
            --disable-popup-blocking \
            --no-default-browser-check \
            --no-first-run \
            "${{ secrets.SECRET_URL }}" &
          
          sleep 5

      # 12. Manage Cloudflared Tunnel
      - name: Manage Cloudflared Tunnel
        run: |
          TUNNEL_NAME="github-actions-tunnel"
          HOSTNAME="${{ secrets.VNC_HOSTNAME }}"

          EXISTING_TUNNEL=$(cloudflared tunnel list | grep "$TUNNEL_NAME" || true)
          if [ -n "$EXISTING_TUNNEL" ]; then
            TUNNEL_ID=$(echo "$EXISTING_TUNNEL" | awk '{print $1}')
            echo "Existing tunnel: $TUNNEL_ID. Deleting..."
            cloudflared tunnel delete "$TUNNEL_ID"
          fi

          cloudflared tunnel create "$TUNNEL_NAME"
          TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')

          mkdir -p ~/.cloudflared
          cat <<EOL > ~/.cloudflared/config.yml
          tunnel: $TUNNEL_ID
          credentials-file: /home/runner/.cloudflared/$TUNNEL_ID.json
          
          ingress:
            - hostname: "$HOSTNAME"
              service: tcp://localhost:5900
            - service: http_status:404
          EOL

          cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$HOSTNAME"

      # 13. Start Cloudflared
      - name: Start Cloudflared
        run: |
          nohup cloudflared tunnel --config ~/.cloudflared/config.yml run "github-actions-tunnel" &
          sleep 10

      # 14. Keep the container running
      - name: Keep Service Running
        run: |
          echo "Workflow complete; keeping container alive..."
          while true; do sleep 1000; done
